[package]
name = "aoc2023-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["days/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
